In [24]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
import  warnings

warnings.filterwarnings('ignore')

In [25]:
performance=pd.read_csv(r'C:\Users\suraj\Downloads\Student_Performance.csv')
performance.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.5
1,4,82,No,4,2,65.6
2,8,51,Yes,7,2,45.6
3,5,52,Yes,5,2,37.0
4,7,75,No,8,5,67.3


# Identifying input and target field

In [3]:
performance.columns

Index(['Hours Studied', 'Previous Scores', 'Extracurricular Activities',
       'Sleep Hours', 'Sample Question Papers Practiced', 'Performance Index'],
      dtype='object')

In [4]:
performance.corr(numeric_only=True)['Performance Index']

Hours Studied                       0.374297
Previous Scores                     0.915321
Sleep Hours                         0.047259
Sample Question Papers Practiced    0.042876
Performance Index                   1.000000
Name: Performance Index, dtype: float64

In [5]:
input_field= 'Previous Scores'
target_field= 'Performance Index'

## predict performance based on previous score

In [6]:
training_data,test_data= train_test_split(performance[[input_field,target_field]],test_size=0.3,random_state=0)


In [7]:
#instantiating a linear Regression model
model= LinearRegression()

# Training the model

In [8]:
model.fit(training_data[[input_field]],training_data[[target_field]])

LinearRegression()

# Making Predictions

In [9]:
model.predict(test_data[[input_field]])

array([[53.66679101],
       [46.52962432],
       [77.11748153],
       ...,
       [69.98031485],
       [40.41205288],
       [86.29383869]])

# Evaluating the model

In [10]:
from sklearn.metrics import mean_absolute_error
print(f'mean absolute erorr: {mean_absolute_error(test_data[target_field],model.predict(test_data[[input_field]]))}')

mean absolute erorr: 6.5980257186276114


In [11]:
from sklearn.metrics import mean_squared_error
print(f'mean squared erorr: {mean_squared_error(test_data[target_field],model.predict(test_data[[input_field]]))}')

mean squared erorr: 60.064257247635396


In [12]:
from sklearn.metrics import root_mean_squared_error
print(f'root mean squared  erorr: {root_mean_squared_error(test_data[target_field],model.predict(test_data[[input_field]]))}')

root mean squared  erorr: 7.750113369985977


In [13]:
from sklearn.metrics import r2_score
print(f' r2 score: {r2_score(test_data[target_field],model.predict(test_data[[input_field]]))}')

 r2 score: 0.8340274721240245


In [14]:
model_2= LinearRegression(positive=True)
model_2.fit(training_data[[input_field]],training_data[[target_field]])
print(f'mean absolute erorr: {mean_absolute_error(test_data[target_field],model_2.predict(test_data[[input_field]]))}')
print(f'mean squared erorr : {mean_squared_error(test_data[target_field],model_2.predict(test_data[[input_field]]))}')
print(f'root mean squared  erorr: {root_mean_squared_error(test_data[target_field],model_2.predict(test_data[[input_field]]))}')
print(f'r2 score: {r2_score(test_data[target_field],model_2.predict(test_data[[input_field]]))}')

mean absolute erorr: 6.598025718627611
mean squared erorr : 60.06425724763536
root mean squared  erorr: 7.750113369985975
r2 score: 0.8340274721240246


In [15]:
def adjusted_r2(actual,prediction,inputs):
    return ((1-r2_score(actual,prediction))* (len(actual)-1))/ (len(actual)-inputs-1)
adjusted_r2(test_data[target_field],model_2.predict(test_data[[input_field]]),model_2.n_features_in_)

0.16602788895932294

In [16]:
model.coef_

array([[1.01959524]])

In [17]:
model.intercept_

array([-14.64609008])

In [18]:
model.n_features_in_

1

In [19]:
model.feature_names_in_

array(['Previous Scores'], dtype=object)

# Linear Regression using  multiple  Input fields(Multiple Linear Regression)

In [20]:
input_fields = ['Hours Studied', 'Previous Scores',
                'Sleep Hours', 'Sample Question Papers Practiced']

training_data, test_data = train_test_split(
    performance[input_fields + [target_field]],
    test_size=0.3,
    random_state=0
)

model_3 = LinearRegression()

model_3.fit(
    training_data[input_fields],
    training_data[target_field]
)

print(f'mean absolute error: {mean_absolute_error(test_data[target_field], model_3.predict(test_data[input_fields]))}')
print(f'mean squared error: {mean_squared_error(test_data[target_field], model_3.predict(test_data[input_fields]))}')
print(f'root mean squared error: {root_mean_squared_error(test_data[target_field], model_3.predict(test_data[input_fields]))}')
print(f'r2 score: {r2_score(test_data[target_field], model_3.predict(test_data[input_fields]))}')

mean absolute error: 1.5763108682653726
mean squared error: 3.9333873749438557
root mean squared error: 1.9832769284554932
r2 score: 0.9891310693638756


# Saving model for future use

In [21]:
import joblib as jb

#save model
linear_regression_model={'inputs':input_fields,'target': target_field,'model': model_3}
jb.dump(linear_regression_model,'linear_regression.joblib')

['linear_regression.joblib']

In [22]:
saved_model= jb.load('linear_regression.joblib')

input_values={}
for feature in saved_model['inputs']:
    value= input(f'enter the {feature.lower()}:')
    input_values.update({feature:float(value)})

print(f'predicted performance:{saved_model['model'].predict(pd.DataFrame(input_values,index=[0]))}')

enter the hours studied: 23
enter the previous scores: 34
enter the sleep hours: 4
enter the sample question papers practiced: 34


predicted performance:[75.71045239]
